"""sync database with ORM models

Revision ID: 5e7fd5ae511e
Revises: a8385547f34c
Create Date: 2025-12-11 21:51:00.962736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7fd5ae511e'
down_revision: Union[str, Sequence[str], None] = 'a8385547f34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_embeddings_vector_ivfflat'), table_name='embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_embeddings_content_trgm'), table_name='embeddings', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_embeddings_embedding_ivfflat'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_embeddings_embedding_ivfflat'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('ix_embeddings_content_trgm'), 'embeddings', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_embeddings_vector_ivfflat'), 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
