"""sync database with ORM models

Revision ID: a8385547f34c
Revises: 14eb431e90a9
Create Date: 2025-12-11 21:45:42.447287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8385547f34c'
down_revision: Union[str, Sequence[str], None] = '14eb431e90a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawing_version_id', sa.UUID(), nullable=False),
    sa.Column('item_number', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('contact_info', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rules_json', sa.JSON(), nullable=True),
    sa.Column('embedding_stats', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_customers',
    sa.Column('drawing_version_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], )
    )
    op.create_table('drawing_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawing_version_id', sa.UUID(), nullable=False),
    sa.Column('standard_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='issue_severity_enum'), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'ignored', name='issue_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standard_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drawing_projects',
    sa.Column('drawing_version_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], )
    )
    op.create_table('drawing_text_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawing_version_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('DIMENSIONS', 'NOTES', 'JSON', 'SUMMARY', 'MANUAL', name='chunk_source_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drawing_version_id'], ['drawing_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawing_text_chunks_drawing_version_id'), 'drawing_text_chunks', ['drawing_version_id'], unique=False)
    op.create_index('ix_drawing_text_chunks_dv_src', 'drawing_text_chunks', ['drawing_version_id', 'source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_index(op.f('ix_embeddings_embedding_ivfflat'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    #op.create_index(op.f('ix_embeddings_content_trgm'), 'embeddings', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    #op.create_index(op.f('idx_embeddings_vector_ivfflat'), 'embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('ix_drawing_text_chunks_dv_src', table_name='drawing_text_chunks')
    op.drop_index(op.f('ix_drawing_text_chunks_drawing_version_id'), table_name='drawing_text_chunks')
    op.drop_table('drawing_text_chunks')
    op.drop_table('drawing_projects')
    op.drop_table('drawing_issues')
    op.drop_table('drawing_customers')
    op.drop_table('standard_documents')
    op.drop_table('projects')
    op.drop_table('customers')
    op.drop_table('bom_items')
    # ### end Alembic commands ###
