"""create drawings and chunks tables

Revision ID: b2747a985e17
Revises: 
Create Date: 2025-12-07 18:23:50.977834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector  # <-- add this import

# revision identifiers, used by Alembic.
revision: str = 'b2747a985e17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    #op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('ingested_path', sa.String(), nullable=False),
    sa.Column('dxf_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('png_path', sa.String(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('json_path', sa.String(), nullable=True),
    sa.Column('dwg_version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawings_document_id'), 'drawings', ['document_id'], unique=True)
    op.create_index(op.f('ix_drawings_id'), 'drawings', ['id'], unique=False)
    op.create_table('drawing_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drawing_id', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=3072), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawing_chunks_chunk_type'), 'drawing_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_drawing_chunks_drawing_id'), 'drawing_chunks', ['drawing_id'], unique=False)
    op.create_index(op.f('ix_drawing_chunks_id'), 'drawing_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawing_chunks_id'), table_name='drawing_chunks')
    op.drop_index(op.f('ix_drawing_chunks_drawing_id'), table_name='drawing_chunks')
    op.drop_index(op.f('ix_drawing_chunks_chunk_type'), table_name='drawing_chunks')
    op.drop_table('drawing_chunks')
    op.drop_index(op.f('ix_drawings_id'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_document_id'), table_name='drawings')
    op.drop_table('drawings')
    # ### end Alembic commands ###
